### ISSUE TITLE
example runs failed

### ISSUE THREAD

**Issue by freealong** [jhu-lcsr/handeye_calib_camodocal#2] opened 2017-04-30 07:43 UTC
OS: ubuntu16.04
The following example doesn't work...
```bash
# roslaunch handeye_calib_camodocal handeye_file.launch
```
terminal output:
```bash
... logging to /home/yongqi/.ros/log/19d39188-2cb1-11e7-a55b-0c82683d98b6/roslaunch-yongqi-OptiPlex-7010-27081.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://yongqi-OptiPlex-7010:41028/

SUMMARY
========

PARAMETERS
 * /handeye_calib_camodocal/ARTagTF: /ar_marker_0
 * /handeye_calib_camodocal/EETF: /ee_link
 * /handeye_calib_camodocal/baseTF: /base_link
 * /handeye_calib_camodocal/cameraTF: /camera_link
 * /handeye_calib_camodocal/load_transforms_from_file: True
 * /handeye_calib_camodocal/output_calibrated_transform_filename: /home/yongqi/catk...
 * /handeye_calib_camodocal/transform_pairs_record_filename: /home/yongqi/catk...
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    handeye_calib_camodocal (handeye_calib_camodocal/handeye_calib_camodocal)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[handeye_calib_camodocal-1]: started with pid [27099]
Calibrated output file: /home/yongqi/catkin_ws/src/handeye_calib_camodocal/launch/CalibratedTransform.yml
Transform pairs loading file: TransformPairsOutput.yml
[ INFO] [1493537679.566074523]: Adding first transformation.
EE transform: 
  0.638483   0.767534  0.0568427   0.612118
0.00850229  0.0668179  -0.997729 -0.0399105
 -0.769589   0.637516  0.0361363   0.261381
         0          0          0          1
Cam transform: 
-0.164386 -0.213826 -0.962941  0.764291
 0.161875  0.957139 -0.240171 -0.122489
 0.973023 -0.195357 -0.122727  0.200385
        0         0         0         1
[ INFO] [1493537679.592253502]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.215213 vs Cam:0.246387
EE transform: 
 0.433981  0.775651 -0.458286   0.61283
-0.578521 -0.150023 -0.801752 -0.251463
-0.690633  0.613073  0.383623  0.221866
        0         0         0         1
Cam transform: 
 -0.127277  -0.111455  -0.985585   0.752881
 -0.464759   0.884533 -0.0400092   0.117874
  0.876242   0.452967   -0.16438   0.147451
         0          0          0          1
[ INFO] [1493537679.592787035]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.195441 vs Cam:0.216132
EE transform: 
 0.709849  0.661286  0.242519  0.603354
 0.483669 -0.207335 -0.850339 -0.226261
-0.512035  0.720911  -0.46702  0.203122
        0         0         0         1
Cam transform: 
 -0.0013274  0.00287129   -0.999995    0.775879
   0.647853    0.761765   0.0013273   0.0894315
   0.761765   -0.647848 -0.00287134    0.159541
          0           0           0           1
[ INFO] [1493537679.593285912]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.229358 vs Cam:0.245743
EE transform: 
  0.456608   0.884121 -0.0991898   0.443182
  0.285236  -0.251085  -0.924985  -0.192034
 -0.842704   0.394063  -0.366831   0.230983
         0          0          0          1
Cam transform: 
-0.378376  0.174054 -0.909141  0.879284
 0.348826  0.936566 0.0341261 0.0882483
  0.85741  -0.30422 -0.415088  0.252881
        0         0         0         1
[ INFO] [1493537679.593808575]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.387457 vs Cam:0.366207
EE transform: 
  0.323211   0.940599   0.103963   0.248849
-0.0689631   0.132979  -0.988717  -0.173242
 -0.943811   0.312394   0.107847    0.24186
         0          0          0          1
Cam transform: 
 -0.505514   -0.28428  -0.814641     1.0135
-0.0235831   0.948363   -0.31631  0.0714151
  0.862496  -0.140688  -0.486115   0.385871
         0          0          0          1
[ INFO] [1493537679.594311224]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.342398 vs Cam:0.342725
EE transform: 
   0.46462    0.88284  0.0687151   0.432093
 0.0525137  0.0499925  -0.997368   -0.31921
 -0.883951   0.467006 -0.0231337   0.178805
         0          0          0          1
Cam transform: 
-0.395441 -0.197478 -0.897011  0.902994
   0.1456  0.950787 -0.273503  0.190431
 0.906878 -0.238759 -0.347227  0.217779
        0         0         0         1
[ INFO] [1493537679.594814846]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.290927 vs Cam:0.272425
EE transform: 
-0.153963  0.959983  0.233939  0.371358
0.0283561  0.240958 -0.970121 -0.201852
 -0.98767 -0.142729  -0.06432  0.282538
        0         0         0         1
Cam transform: 
-0.824707 -0.238584 -0.512772  0.934864
-0.013887  0.914932 -0.403368  0.065755
 0.565389  -0.32554 -0.757865  0.298794
        0         0         0         1
[ INFO] [1493537679.595326427]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.190786 vs Cam:0.145262
EE transform: 
 0.418462   0.80981  0.411214  0.593949
-0.250154  0.538016  -0.80496 -0.228291
-0.873105  0.233978  0.427717  0.285505
        0         0         0         1
Cam transform: 
-0.367026 -0.701436 -0.610965  0.762706
-0.197372  0.700571 -0.685743 0.0218338
  0.90903 -0.131098 -0.395572   0.18397
        0         0         0         1
[ INFO] [1493537679.595857897]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.217562 vs Cam:0.181829
EE transform: 
 0.677224  0.731047 0.0832987  0.642735
-0.494061  0.535712 -0.684774 -0.252373
-0.545226  0.422591  0.723979  0.225948
        0         0         0         1
Cam transform: 
   0.0976 -0.689456 -0.717722  0.753887
-0.346197  0.652607 -0.673983 0.0429672
 0.933071  0.314254 -0.174993  0.125701
        0         0         0         1
[ INFO] [1493537679.596374713]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.0645175 vs Cam:0.0572455
EE transform: 
  0.612387   0.763326   0.205709   0.637671
  0.164239   0.131689  -0.977591 -0.0885319
  -0.77331   0.632449 -0.0447231   0.227536
         0          0          0          1
Cam transform: 
 -0.174813  -0.263647  -0.948647   0.765482
  0.297239   0.904399  -0.306124 -0.0875266
  0.938663   -0.33549 -0.0797345   0.155072
         0          0          0          1
[ INFO] [1493537679.596866538]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.166543 vs Cam:0.155018
EE transform: 
  0.624052   0.778644 -0.0653676   0.682684
  -0.40703   0.252525  -0.877814  -0.190556
 -0.666998   0.574408    0.47452   0.253441
         0          0          0          1
Cam transform: 
  -0.0156266    -0.445582    -0.895105     0.701242
   -0.243935     0.869863    -0.428758 -0.000550737
    0.969666     0.211647    -0.122286     0.128369
           0            0            0            1
[ INFO] [1493537679.597348153]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.107402 vs Cam:0.10879
EE transform: 
  0.643567   0.765191  0.0174386   0.712786
  0.254161  -0.192161   -0.94788 -0.0317913
 -0.721958   0.614456   -0.31815   0.224841
         0          0          0          1
Cam transform: 
 -0.0989447   0.0423206   -0.994193    0.718351
   0.387674    0.921796 0.000656462   -0.125335
   0.916471   -0.385358   -0.107613    0.101812
          0           0           0           1
[ INFO] [1493537679.597837399]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.186286 vs Cam:0.167712
EE transform: 
 0.631684  0.773867 0.0458826  0.718126
 0.351244 -0.232942 -0.906844  0.112637
-0.691089  0.588954 -0.418962  0.247451
        0         0         0         1
Cam transform: 
 -0.11272  0.100454 -0.988536  0.722855
 0.495192  0.868203 0.0317608 -0.267481
  0.86144 -0.485935 -0.147608  0.126984
        0         0         0         1
[ INFO] [1493537679.598309160]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.122085 vs Cam:0.11748
EE transform: 
 0.214104  0.968786  0.124954  0.528412
 0.820688 -0.109032 -0.560877 0.0474746
-0.529745  0.222634 -0.818415  0.245198
        0         0         0         1
Cam transform: 
-0.354624  0.433515 -0.828436  0.862123
  0.85652  0.505959  -0.10188 -0.185446
 0.374988 -0.745701 -0.550739  0.216721
        0         0         0         1
[ INFO] [1493537679.598798316]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.115361 vs Cam:0.135141
EE transform: 
 0.593263  0.798971   0.09841  0.633696
 0.363423 -0.156741 -0.918344 -0.143423
-0.718306  0.580584 -0.383353  0.215253
        0         0         0         1
Cam transform: 
  -0.177395   0.0416623   -0.983258    0.763908
   0.501263    0.863618  -0.0538427 -0.00403508
   0.846916   -0.502422   -0.174085    0.135334
          0           0           0           1
[ INFO] [1493537679.599272100]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.202728 vs Cam:0.135966
EE transform: 
  0.771397   0.281163  -0.570871   0.776923
 -0.522504  -0.232209  -0.820407  0.0369184
  -0.36323   0.931142 -0.0322165   0.171742
         0          0          0          1
Cam transform: 
 0.373449  0.257277  -0.89126  0.726359
 -0.31825  0.937994  0.137417 -0.182011
 0.871351  0.232326  0.432172 0.0841736
        0         0         0         1
[ INFO] [1493537679.599755426]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.211066 vs Cam:0.192321
EE transform: 
  0.59232  0.312115 -0.742793  0.756832
-0.766905 -0.064235 -0.638538 -0.180032
-0.247011   0.94787  0.201315  0.198352
        0         0         0         1
Cam transform: 
   0.35259   0.253018  -0.900923   0.686074
 -0.621796   0.782826 -0.0234983  0.0204989
  0.699321   0.568476   0.433343  0.0982884
         0          0          0          1
[ INFO] [1493537679.600241630]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.218805 vs Cam:0.188602
EE transform: 
  0.786341   0.439637   0.434036   0.770384
  0.479322 0.00908998  -0.877592  0.0902576
 -0.389767    0.89813   -0.20358   0.184675
         0          0          0          1
Cam transform: 
 0.134203 -0.329043  -0.93473  0.728758
 0.671974   0.72348 -0.158201 -0.274474
 0.728313 -0.606883  0.318201 0.0945141
        0         0         0         1
[ INFO] [1493537679.600736906]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.102906 vs Cam:0.101342
EE transform: 
 0.665485  0.675559  0.317412  0.554426
 0.414056 0.0197006 -0.910038 0.0117472
-0.621038  0.737043 -0.266609  0.193611
        0         0         0         1
Cam transform: 
-0.0879954  -0.170409  -0.981436   0.857683
  0.528511   0.827159  -0.191008  -0.159951
  0.844354  -0.535508  0.0172769   0.212416
         0          0          0          1
[ INFO] [1493537679.601212578]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.245913 vs Cam:0.226488
EE transform: 
  0.211806     0.9765 -0.0398361   0.468647
 -0.961238   0.200787  -0.188962  -0.233015
 -0.176523  0.0783153   0.981176   0.312372
         0          0          0          1
Cam transform: 
 0.122497 -0.698436 -0.705111  0.814256
-0.912926   0.19939 -0.356104 0.0879747
 0.389308  0.687336 -0.613196  0.267508
        0         0         0         1
[ INFO] [1493537679.601692677]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.203669 vs Cam:0.170966
EE transform: 
  0.621962   0.782692 -0.0235887   0.679652
 -0.719302   0.559166  -0.412236  -0.231721
 -0.309464   0.273363   0.910771   0.250024
         0          0          0          1
Cam transform: 
 0.283423 -0.704145 -0.651038   0.71956
-0.592429  0.405286 -0.696255 0.0135736
 0.754122  0.583029 -0.302288  0.107028
        0         0         0         1
[ INFO] [1493537679.602164631]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.328268 vs Cam:0.288981
EE transform: 
  0.67922  0.733721 0.0177239  0.632855
-0.608679  0.576631 -0.544983 -0.365025
-0.410086  0.359375  0.838259  0.221003
        0         0         0         1
Cam transform: 
 0.295033 -0.721063 -0.626916   0.74937
-0.502125  0.441212 -0.743776  0.152977
 0.812912  0.534228 -0.231892  0.114329
        0         0         0         1
[ INFO] [1493537679.602650480]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.249251 vs Cam:0.18365
EE transform: 
  0.812029   0.579104 -0.0724385    0.69914
  0.414438   -0.65957  -0.627064   0.192743
 -0.410913   0.479173  -0.775592   0.240755
         0          0          0          1
Cam transform: 
 0.216836  0.465516 -0.858066  0.764563
 0.607482   0.62371  0.491886  -0.29749
 0.764165 -0.627918  -0.14755  0.144691
        0         0         0         1
[ INFO] [1493537679.603121882]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.170334 vs Cam:0.152798
EE transform: 
  0.804583   0.591943 -0.0474213   0.501879
  0.229391  -0.383462  -0.894615  0.0897372
 -0.547746   0.708915  -0.444314   0.268606
         0          0          0          1
Cam transform: 
 0.131482  0.169286 -0.976757  0.852262
 0.443435  0.871194  0.210682 -0.185114
  0.88661 -0.460829  0.039479  0.308489
        0         0         0         1
[ INFO] [1493537679.603598426]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.112103 vs Cam:0.105423
EE transform: 
 0.0667841   0.853922  -0.516098   0.709308
 -0.751424   0.383345   0.537037 -0.0759432
  0.656431   0.351943   0.667259   0.304078
         0          0          0          1
Cam transform: 
   0.59165 -0.0364445  -0.805371   0.670302
 -0.730477  -0.446907  -0.516408  -0.127621
 -0.341105   0.893838  -0.291034   0.152911
         0          0          0          1
[ INFO] [1493537679.604095246]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.249415 vs Cam:0.238847
EE transform: 
 -0.317105   0.928469  -0.193362   0.620601
-0.0520595   0.186536   0.981068  -0.272426
   0.94696   0.321168 -0.0108159   0.351227
         0          0          0          1
Cam transform: 
 0.442358  0.298281 -0.845782  0.660235
-0.106876 -0.918817 -0.379937 0.0909693
-0.890448  0.258462 -0.374567  0.225992
        0         0         0         1
[ INFO] [1493537679.604582524]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.162403 vs Cam:0.144185
EE transform: 
 -0.31537  0.918887  0.237041  0.661038
  0.24915  -0.16085  0.955014  0.100551
 0.915678  0.360242 -0.178213   0.32659
        0         0         0         1
Cam transform: 
  0.370902  0.0925142  -0.924053   0.706948
   0.15567   -0.98714 -0.0363468  -0.253602
 -0.915532  -0.130366  -0.380534   0.218013
         0          0          0          1
[ INFO] [1493537679.605068559]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.167866 vs Cam:0.147663
EE transform: 
0.0108778  0.742046  -0.67026  0.684698
-0.848225  0.361808  0.386793 -0.190969
 0.529524  0.564324  0.633358   0.25176
        0         0         0         1
Cam transform: 
    0.52301   0.0384859   -0.851457    0.699199
  -0.828886   -0.209705   -0.518624 -0.00268676
  -0.198515    0.977007  -0.0777775    0.143686
          0           0           0           1
[ INFO] [1493537679.605563702]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.174251 vs Cam:0.169405
EE transform: 
  0.127525   0.713096  -0.689371   0.664034
  -0.98397   0.178315 0.00242873  -0.189673
  0.124657   0.678011   0.724405   0.188995
         0          0          0          1
Cam transform: 
  0.297171 -0.0324921  -0.954271   0.751153
 -0.946831   0.119021  -0.298906  0.0243991
  0.123291    0.99236   0.004605   0.117024
         0          0          0          1
[ INFO] [1493537679.606031131]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.174251 vs Cam:0.169444
EE transform: 
  0.127537   0.713093  -0.689371   0.664035
 -0.983968   0.178331 0.00242899  -0.189672
  0.124668   0.678009   0.724405   0.188996
         0          0          0          1
Cam transform: 
  0.297921 -0.0320348  -0.954053   0.751255
 -0.946797   0.117537  -0.299602  0.0244031
  0.121734   0.992552 0.00468615   0.116934
         0          0          0          1
[ INFO] [1493537679.606507513]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.194746 vs Cam:0.169552
EE transform: 
 0.301047  0.820638   0.48572  0.688924
 0.849563 -0.462156  0.254272  0.118761
 0.433143  0.336102 -0.836315  0.178614
        0         0         0         1
Cam transform: 
 0.338239  0.251229 -0.906906  0.795671
 0.910939 -0.329279  0.248527 -0.244215
-0.236188 -0.910198 -0.340229 0.0866057
        0         0         0         1
[ INFO] [1493537679.606976695]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.201437 vs Cam:0.157416
EE transform: 
  0.36784  0.914939  0.166073  0.470847
 0.898307 -0.395784  0.190785 0.0952608
 0.240286 0.0790065 -0.967482  0.309837
        0         0         0         1
Cam transform: 
  0.276986   0.543839  -0.792161   0.863331
  0.958611  -0.212945   0.188995  -0.191875
-0.0659045  -0.811723  -0.580313   0.301165
         0          0          0          1
[ INFO] [1493537679.607457110]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.239668 vs Cam:0.218786
EE transform: 
 0.713634  0.676834  0.180616  0.425799
 0.584897  -0.43381  -0.68535 0.0983482
-0.385516  0.594731  -0.70546  0.201296
        0         0         0         1
Cam transform: 
 0.125093  0.264966 -0.956109  0.952171
 0.729179  0.628936  0.269699    -0.172
 0.672793 -0.730912 -0.114532   0.30097
        0         0         0         1
[ INFO] [1493537679.607958114]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.348903 vs Cam:0.289647
EE transform: 
 0.662312  0.605825  0.440815  0.571357
  0.74147 -0.614447 -0.269586  0.290935
 0.107535  0.505401 -0.856157  0.158362
        0         0         0         1
Cam transform: 
 0.432265  0.214714 -0.875811  0.915636
 0.862817  0.183809  0.470914  -0.36924
 0.262094 -0.959225 -0.105805  0.190188
        0         0         0         1
[ INFO] [1493537679.608427480]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.185299 vs Cam:0.127593
EE transform: 
  0.497426   0.845774   -0.19296   0.578632
  0.858999  -0.511284 -0.0266528   0.135965
   -0.1212  -0.152494  -0.980845   0.309152
         0          0          0          1
Cam transform: 
 0.171758  0.808071  -0.56349  0.820531
 0.943272 0.0300799  0.330656  -0.23634
 0.284143 -0.588317 -0.757064  0.212836
        0         0         0         1
[ INFO] [1493537679.608907582]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.115444 vs Cam:0.0644161
EE transform: 
 0.846406  0.512564 -0.144481  0.663868
 0.117042  -0.44372  -0.88849 0.0400476
-0.519516  0.735113 -0.435559  0.196143
        0         0         0         1
Cam transform: 
 0.209615  0.217129 -0.953371   0.78508
 0.314646  0.908191   0.27602 -0.149685
 0.925775 -0.357832  0.122051  0.145818
        0         0         0         1
[ INFO] [1493537679.609359233]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.0920312 vs Cam:0.10319
EE transform: 
 0.371265  0.873927 -0.313711  0.582489
-0.671523 0.0193811  -0.74073 -0.110443
-0.641264  0.485671  0.594058  0.210225
        0         0         0         1
Cam transform: 
  0.166593 -0.0606493  -0.984159    0.78221
  -0.50926   0.849387  -0.138548 -0.0283258
  0.844335   0.524274   0.110615   0.162171
         0          0          0          1
[ INFO] [1493537679.609801922]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.078633 vs Cam:0.103478
EE transform: 
 -0.194412   0.897314  -0.396271   0.689605
 -0.903413  -0.321179  -0.284057 -0.0355685
 -0.382163   0.302772   0.873087   0.248729
         0          0          0          1
Cam transform: 
 -0.310953    -0.3317  -0.890665    0.73046
 -0.916208   0.353807   0.188106 -0.0857941
  0.252729   0.874526  -0.413923   0.109739
         0          0          0          1
[ INFO] [1493537679.610244076]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.140734 vs Cam:0.158002
EE transform: 
0.00380638   0.997935 -0.0641172   0.719795
 -0.715418 -0.0420809  -0.697428  -0.115366
 -0.698686  0.0485253   0.713781   0.311563
         0          0          0          1
Cam transform: 
 -0.394316  -0.544214  -0.740504   0.669897
 -0.714264   0.688504  -0.125655 -0.0479955
  0.578223   0.479367  -0.660201  0.0978907
         0          0          0          1
[ INFO] [1493537679.610682751]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.289567 vs Cam:0.235117
EE transform: 
 0.160943  0.808859 -0.565548  0.692687
-0.467261 -0.442286 -0.765539  0.238203
-0.869347  0.387467  0.306765  0.264692
        0         0         0         1
Cam transform: 
-0.429407  0.100189 -0.897537  0.760462
-0.426432  0.853567  0.299298 -0.352083
 0.796094  0.511259 -0.323804   0.14987
        0         0         0         1
[ INFO] [1493537679.611129257]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.0880918 vs Cam:0.0919122
EE transform: 
  0.701298    0.71029 -0.0605818    0.52559
 0.0355382  -0.119712  -0.992172 -0.0362252
 -0.711982   0.693655  -0.109196   0.245273
         0          0          0          1
Cam transform: 
-0.0591548 -0.0404454  -0.997429   0.830807
  0.172508   0.983732 -0.0501209 -0.0909857
   0.98323  -0.175029 -0.0512154    0.25544
         0          0          0          1
[ INFO] [1493537679.611573895]: Hand Eye Calibration Transform Pair Added
L2Norm EE: 0.178307 vs Cam:0.159159
EE transform: 
  0.791774   0.610124 -0.0290322   0.764747
-0.0922811  0.0725003   -0.99309 -0.0815968
 -0.603804   0.788982   0.113707   0.179162
         0          0          0          1
Cam transform: 
  0.121676  -0.217217   -0.96851   0.704562
 0.0926826   0.973983  -0.206801  -0.104441
  0.988233 -0.0646013   0.138643  0.0539669
         0          0          0          1
[handeye_calib_camodocal-1] process has died [pid 27099, exit code -11, cmd /home/yongqi/catkin_ws/devel/lib/handeye_calib_camodocal/handeye_calib_camodocal __name:=handeye_calib_camodocal __log:=/home/yongqi/.ros/log/19d39188-2cb1-11e7-a55b-0c82683d98b6/handeye_calib_camodocal-1.log].
log file: /home/yongqi/.ros/log/19d39188-2cb1-11e7-a55b-0c82683d98b6/handeye_calib_camodocal-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

The process died when it runs to
```c++
ceres::Solve(options, &problem, &summary); // line 334 in HandEyeCalibration.cc (camodocal library)
```

**Comment by ahundt** [comment] 2017-05-10 15:41
Sorry for the delay, just came across this. Did you try the example?

**Comment by fjonath1** [comment] 2017-05-10 19:17
I couldn't reproduce this problem in my 14.04 machine.
Could you tell us what did you use for installing ceres in your machine?

**Comment by freealong** [comment] 2017-05-11 14:06
At the beginning, I installed camodocal library from the src. I did not install ceres because it seems ceres is inside the camodocal library.
After i came cross the problem, I thought it maybe something wrong with the ceres inside camodocal, so i installed ceres from src(https://github.com/ceres-solver/ceres-solver). But it still doesn't work.

**Comment by ahundt** [comment] 2017-05-11 18:21
did you delete the build folder for camodocal and rebuild, ensuring it detects the installed ceres?

**Comment by alessmosca** [comment] 2017-06-06 15:34
I got the same problem !! 
Solutions ?

**Comment by ahundt** [comment] 2017-06-06 15:47
@alessmosca you're saying the example also does not work for you on 16.04?

**Comment by ahundt** [comment] 2017-06-06 16:15
We run this once or twice a month on 14.04 with no problems, so I'm not sure what could be going on with 16.04.

**Comment by ahundt** [comment] 2017-06-06 19:22
I've tested 16.04 now. #4 should hopefully solve your problem, check the updated README.md instructions.

**Comment by alessmosca** [comment] 2017-06-07 07:00
Yesterday, in the end, I manage to make it working properly. Apparently not always is able to find a solution for the calibration, probably depending by the poses selected and by the calibration of the camera, as is written in the readme. Anyway thanks for the help!! :)

**Comment by ahundt** [comment] 2017-06-07 19:05
Great, I'll close this and the other issue then as the original creator hasn't replied. Feel free to ask if there are more issues.

**Closed by ahundt** 2017-06-07 19:05 UTC
